# callsign_utils.py
# Utilidades para prefijos ITU y país de indicativo

ITU_PREFIXES = {
    "AA": "USA",
    "AB": "USA",
    "AC": "USA",
    "AD": "USA",
    "AE": "USA",
    "AF": "USA",
    "AG": "USA",
    "AH": "USA",
    "AI": "USA",
    "AJ": "USA",
    "AK": "USA",
    "AL": "USA",
    "AM": "ESP",
    "AN": "ESP",
    "AO": "ESP",
    "AP": "PAK",
    "AQ": "PAK",
    "AR": "PAK",
    "AS": "PAK",
    "AT": "IND",
    "AU": "IND",
    "AV": "IND",
    "AW": "IND",
    "AX": "AUS",
    "AY": "ARG",
    "AZ": "ARG",
    "A2": "BWA",
    "A3": "TON",
    "A4": "OMN",
    "A5": "BTN",
    "A6": "ARE",
    "A7": "QAT",
    "A8": "LBR",
    "A9": "BHR",
    "B": "CHN",
    "BM": "TWN",
    "BN": "TWN",
    "BO": "TWN",
    "BP": "TWN",
    "BQ": "TWN",
    "BU": "TWN",
    "BV": "TWN",
    "BW": "TWN",
    "BX": "TWN",
    "CA": "CHL",
    "CB": "CHL",
    "CC": "CHL",
    "CD": "CHL",
    "CE": "CHL",
    "CF": "CAN",
    "CG": "CAN",
    "CH": "CAN",
    "CI": "CAN",
    "CJ": "CAN",
    "CK": "CAN",
    "CL": "CUB",
    "CM": "CUB",
    "CN": "MAR",
    "CO": "CUB",
    "CP": "BOL",
    "CQ": "PRT",
    "CR": "PRT",
    "CS": "PRT",
    "CT": "PRT",
    "CU": "PRT",
    "CV": "URY",
    "CW": "URY",
    "CX": "URY",
    "CY": "CAN",
    "CZ": "CAN",
    "C2": "NRU",
    "C3": "AND",
    "C4": "CYP",
    "C5": "GMB",
    "C6": "BHS",
    "C7": "WMO",
    "C8": "MOZ",
    "C9": "MOZ",
    "DA": "DEU",
    "DB": "DEU",
    "DC": "DEU",
    "DD": "DEU",
    "DE": "DEU",
    "DF": "DEU",
    "DG": "DEU",
    "DH": "DEU",
    "DI": "DEU",
    "DJ": "DEU",
    "DK": "DEU",
    "DL": "DEU",
    "DM": "DEU",
    "DN": "DEU",
    "DO": "DEU",
    "DP": "DEU",
    "DQ": "DEU",
    "DR": "DEU",
    "DS": "KOR",
    "DT": "KOR",
    "DU": "PHL",
    "DV": "PHL",
    "DW": "PHL",
    "DX": "PHL",
    "DY": "PHL",
    "DZ": "PHL",
    "D2": "AGO",
    "D3": "AGO",
    "D4": "CPV",
    "D5": "LBR",
    "D6": "COM",
    "D7": "KOR",
    "D8": "KOR",
    "D9": "KOR",
    "EA": "ESP",
    "EB": "ESP",
    "EC": "ESP",
    "ED": "ESP",
    "EE": "ESP",
    "EF": "ESP",
    "EG": "ESP",
    "EH": "ESP",
    "EI": "IRL",
    "EJ": "IRL",
    "EK": "ARM",
    "EL": "LBR",
    "EM": "UKR",
    "EN": "UKR",
    "EO": "UKR",
    "EP": "IRN",
    "EQ": "IRN",
    "ER": "MDA",
    "ES": "EST",
    "ET": "ETH",
    "EU": "BLR",
    "EV": "BLR",
    "EW": "BLR",
    "EX": "KGZ",
    "EY": "TJK",
    "EZ": "TKM",
    "E2": "THA",
    "E3": "ERI",
    "E4": "PSE",
    "E5": "COK",
    "E6": "NIU",
    "E7": "BIH",
    "F": "FRA",
    "G": "GBR",
    "HA": "HUN",
    "HB": "CHE",
    "HB0": "LIE",
    "HB3Y": "LIE",
    "HBL": "LIE",
    "HC": "ECU",
    "HD": "ECU",
    "HE": "CHE",
    "HF": "POL",
    "HG": "HUN",
    "HH": "HTI",
    "HI": "DOM",
    "HJ": "COL",
    "HK": "COL",
    "HL": "KOR",
    "HM": "PRK",
    "HN": "IRQ",
    "HO": "PAN",
    "HP": "PAN",
    "HQ": "HND",
    "HR": "HND",
    "HS": "THA",
    "HT": "NIC",
    "HU": "SLV",
    "HV": "VAT",
    "HW": "FRA",
    "HX": "FRA",
    "HY": "FRA",
    "HZ": "SAU",
    "H2": "CYP",
    "H3": "PAN",
    "H4": "SLB",
    "H6": "NIC",
    "H7": "NIC",
    "H8": "PAN",
    "H9": "PAN",
    "I": "ITA",
    "JA": "JPN",
    "JB": "JPN",
    "JC": "JPN",
    "JD": "JPN",
    "JE": "JPN",
    "JF": "JPN",
    "JG": "JPN",
    "JH": "JPN",
    "JI": "JPN",
    "JJ": "JPN",
    "JK": "JPN",
    "JL": "JPN",
    "JM": "JPN",
    "JN": "JPN",
    "JO": "JPN",
    "JP": "JPN",
    "JQ": "JPN",
    "JR": "JPN",
    "JS": "JPN",
    "JT": "MNG",
    "JU": "MNG",
    "JV": "MNG",
    "JW": "NOR",
    "JX": "NOR",
    "JY": "JOR",
    "JZ": "IDN",
    "J2": "DJI",
    "J3": "GRD",
    "J4": "GRC",
    "J5": "GNB",
    "J6": "LCA",
    "J7": "DMA",
    "J8": "VCT",
    "K": "USA",
    "LA": "NOR",
    "LB": "NOR",
    "LC": "NOR",
    "LD": "NOR",
    "LE": "NOR",
    "LF": "NOR",
    "LG": "NOR",
    "LH": "NOR",
    "LI": "NOR",
    "LJ": "NOR",
    "LK": "NOR",
    "LL": "NOR",
    "LM": "NOR",
    "LN": "NOR",
    "LO": "ARG",
    "LP": "ARG",
    "LQ": "ARG",
    "LR": "ARG",
    "LS": "ARG",
    "LT": "ARG",
    "LU": "ARG",
    "LV": "ARG",
    "LW": "ARG",
    "LX": "LUX",
    "LY": "LTU",
    "LZ": "BGR",
    "L2": "ARG",
    "L3": "ARG",
    "L4": "ARG",
    "L5": "ARG",
    "L6": "ARG",
    "L7": "ARG",
    "L8": "ARG",
    "L9": "ARG",
    "M": "GBR",
    "N": "USA",
    "OA": "PER",
    "OB": "PER",
    "OC": "PER",
    "OD": "LBN",
    "OE": "AUT",
    "OF": "FIN",
    "OG": "FIN",
    "OH": "FIN",
    "OI": "FIN",
    "OJ": "FIN",
    "OK": "CZE",
    "OL": "CZE",
    "OM": "SVK",
    "ON": "BEL",
    "OO": "BEL",
    "OP": "BEL",
    "OQ": "BEL",
    "OR": "BEL",
    "OS": "BEL",
    "OT": "BEL",
    "OU": "DNK",
    "OV": "DNK",
    "OW": "DNK",
    "OX": "DNK",
    "OY": "DNK",
    "OZ": "DNK",
    "PA": "NLD",
    "PB": "NLD",
    "PC": "NLD",
    "PD": "NLD",
    "PE": "NLD",
    "PF": "NLD",
    "PG": "NLD",
    "PH": "NLD",
    "PI": "NLD",
    "PJ": "ANT",
    "PK": "IDN",
    "PL": "IDN",
    "PM": "IDN",
    "PN": "IDN",
    "PO": "IDN",
    "P": "BRA",
    "PQ": "BRA",
    "PR": "BRA",
    "PS": "BRA",
    "PT": "BRA",
    "PU": "BRA",
    "PV": "BRA",
    "PW": "BRA",
    "PX": "BRA",
    "PY": "BRA",
    "PZ": "SUR",
    "P2": "PNG",
    "P3": "CYP",
    "P4": "ABW",
    "P5": "PRK",
    "P6": "PRK",
    "P7": "PRK",
    "P8": "PRK",
    "P9": "PRK",
    "R": "RUS",
    "SA": "SWE",
    "SB": "SWE",
    "SC": "SWE",
    "SD": "SWE",
    "SE": "SWE",
    "SF": "SWE",
    "SG": "SWE",
    "SH": "SWE",
    "SI": "SWE",
    "SJ": "SWE",
    "SK": "SWE",
    "SL": "SWE",
    "SM": "SWE",
    "SN": "POL",
    "SO": "POL",
    "SP": "POL",
    "SQ": "POL",
    "SR": "POL",
    "SSA": "EGY",
    "SSB": "EGY",
    "SSC": "EGY",
    "SSD": "EGY",
    "SSE": "EGY",
    "SSF": "EGY",
    "SSG": "EGY",
    "SSH": "EGY",
    "SSI": "EGY",
    "SSJ": "EGY",
    "SSK": "EGY",
    "SSL": "EGY",
    "SSM": "EGY",
    "SSN": "SDN",
    "SSO": "SDN",
    "SSP": "SDN",
    "SSQ": "SDN",
    "SSR": "SDN",
    "SSS": "SDN",
    "SST": "SDN",
    "SSU": "SDN",
    "SSV": "SDN",
    "SSW": "SDN",
    "SSX": "SDN",
    "SSY": "SDN",
    "SSZ": "SDN",
    "STA": "SDN",
    "STB": "SDN",
    "STC": "SDN",
    "STD": "SDN",
    "STE": "SDN",
    "STF": "SDN",
    "STG": "SDN",
    "STH": "SDN",
    "STI": "SDN",
    "STJ": "SDN",
    "STK": "SDN",
    "STL": "SDN",
    "STM": "SDN",
    "STN": "SDN",
    "STO": "SDN",
    "STP": "SDN",
    "STQ": "SDN",
    "STR": "SDN",
    "STS": "SDN",
    "STT": "SDN",
    "STU": "SDN",
    "STV": "SDN",
    "STW": "SDN",
    "STX": "SDN",
    "STY": "SDN",
    "STZ": "SDN",
    "SU": "EGY",
    "SV": "GRC",
    "SW": "GRC",
    "SX": "GRC",
    "SY": "GRC",
    "SZ": "GRC",
    "S2": "BGD",
    "S3": "BGD",
    "S5": "SVN",
    "S6": "SGP",
    "S7": "SYC",
    "S8": "ZAF",
    "S9": "STP",
    "TA": "TUR",
    "TB": "TUR",
    "TC": "TUR",
    "TD": "GTM",
    "TE": "CRI",
    "TF": "ISL",
    "TG": "GTM",
    "TH": "FRA",
    "TI": "CRI",
    "TJ": "CMR",
    "TK": "FRA",
    "TL": "CAF",
    "TM": "FRA",
    "TN": "COG",
    "TO": "FRA",
    "TP": "FRA",
    "TQ": "FRA",
    "TR": "GAB",
    "TS": "TUN",
    "TT": "TCD",
    "TU": "CIV",
    "TV": "FRA",
    "TW": "FRA",
    "TX": "FRA",
    "TY": "BEN",
    "TZ": "MLI",
    "T2": "TUV",
    "T3": "KIR",
    "T4": "CUB",
    "T5": "SOM",
    "T6": "AFG",
    "T7": "SMR",
    "T8": "PLW",
    "UA": "RUS",
    "UB": "RUS",
    "UC": "RUS",
    "UD": "RUS",
    "UE": "RUS",
    "UF": "RUS",
    "UG": "RUS",
    "UH": "RUS",
    "UI": "RUS",
    "UJ": "UZB",
    "UK": "UZB",
    "UL": "UZB",
    "UM": "UZB",
    "UN": "KAZ",
    "UO": "KAZ",
    "UP": "KAZ",
    "UQ": "KAZ",
    "UR": "UKR",
    "US": "UKR",
    "UT": "UKR",
    "UU": "UKR",
    "UV": "UKR",
    "UW": "UKR",
    "UX": "UKR",
    "UY": "UKR",
    "UZ": "UKR",
    "VA": "CAN",
    "VB": "CAN",
    "VC": "CAN",
    "VD": "CAN",
    "VE": "CAN",
    "VF": "CAN",
    "VG": "CAN",
    "VH": "AUS",
    "VI": "AUS",
    "VJ": "AUS",
    "VK": "AUS",
    "VL": "AUS",
    "VM": "AUS",
    "VN": "AUS",
    "VO": "CAN",
    "VP": "GBR",
    "VQ": "GBR",
    "VR": "HKG",
    "VS": "GBR",
    "VT": "IND",
    "VU": "IND",
    "VV": "IND",
    "VW": "IND",
    "VX": "CAN",
    "VY": "CAN",
    "VZ": "AUS",
    "V2": "ATG",
    "V3": "BLZ",
    "V4": "KNA",
    "V5": "NAM",
    "V6": "FSM",
    "V7": "MHL",
    "V8": "BRN",
    "W": "USA",
    "XA": "MEX",
    "XB": "MEX",
    "XC": "MEX",
    "XD": "MEX",
    "XE": "MEX",
    "XF": "MEX",
    "XG": "MEX",
    "XH": "MEX",
    "XI": "MEX",
    "XJ": "CAN",
    "XK": "CAN",
    "XL": "CAN",
    "XM": "CAN",
    "XN": "CAN",
    "XO": "CAN",
    "XP": "DNK",
    "XQ": "CHL",
    "XR": "CHL",
    "XS": "CHN",
    "XT": "BFA",
    "XU": "KHM",
    "XV": "VNM",
    "XW": "LAO",
    "XX": "MAC",
    "XY": "MMR",
    "XZ": "MMR",
    "YA": "AFG",
    "YB": "IDN",
    "YC": "IDN",
    "YD": "IDN",
    "YE": "IDN",
    "YF": "IDN",
    "YG": "IDN",
    "YH": "IDN",
    "YI": "IRQ",
    "YJ": "VUT",
    "YK": "SYR",
    "YL": "LVA",
    "YM": "TUR",
    "YN": "NIC",
    "YO": "ROU",
    "YP": "ROU",
    "YQ": "ROU",
    "YR": "ROU",
    "YS": "SLV",
    "YT": "SRB",
    "YU": "SRB",
    "YV": "VEN",
    "YW": "VEN",
    "YX": "VEN",
    "YY": "VEN",
    "Y2": "DEU",
    "Y3": "DEU",
    "Y4": "DEU",
    "Y5": "DEU",
    "Y6": "DEU",
    "Y7": "DEU",
    "Y8": "DEU",
    "Y9": "DEU",
    "ZA": "ALB",
    "ZB": "GBR",
    "ZC": "GBR",
    "ZD": "GBR",
    "ZE": "GBR",
    "ZF": "GBR",
    "ZG": "GBR",
    "ZH": "GBR",
    "ZI": "GBR",
    "ZJ": "GBR",
    "ZK": "NZL",
    "ZL": "NZL",
    "ZM": "NZL",
    "ZN": "GBR",
    "ZO": "GBR",
    "ZP": "PRY",
    "ZQ": "GBR",
    "ZR": "ZAF",
    "ZS": "ZAF",
    "ZT": "ZAF",
    "ZU": "ZAF",
    "ZV": "BRA",
    "ZW": "BRA",
    "ZX": "BRA",
    "ZY": "BRA",
    "ZZ": "BRA",
    "Z2": "ZWE",
    "Z3": "MKD",
    "Z8": "SSD",
    "2": "GBR",
    "3A": "MCO",
    "3B": "MUS",
    "3C": "GNQ",
    "3DA": "SWZ",
    "3DB": "SWZ",
    "3DC": "SWZ",
    "3DD": "SWZ",
    "3DE": "SWZ",
    "3DF": "SWZ",
    "3DG": "SWZ",
    "3DH": "SWZ",
    "3DI": "SWZ",
    "3DJ": "SWZ",
    "3DK": "SWZ",
    "3DL": "SWZ",
    "3DM": "SWZ",
    "3DN": "FJI",
    "3DO": "FJI",
    "3DP": "FJI",
    "3DQ": "FJI",
    "3DR": "FJI",
    "3DS": "FJI",
    "3DT": "FJI",
    "3DU": "FJI",
    "3DV": "FJI",
    "3DW": "FJI",
    "3DX": "FJI",
    "3DY": "FJI",
    "3DZ": "FJI",
    "3E": "PAN",
    "3F": "PAN",
    "3G": "CHL",
    "3H": "CHN",
    "3I": "CHN",
    "3J": "CHN",
    "3K": "CHN",
    "3L": "CHN",
    "3M": "CHN",
    "3N": "CHN",
    "3O": "CHN",
    "3P": "CHN",
    "3Q": "CHN",
    "3R": "CHN",
    "3S": "CHN",
    "3T": "CHN",
    "3U": "CHN",
    "3V": "TUN",
    "3W": "VNM",
    "3X": "GIN",
    "3Y": "NOR",
    "3Z": "POL",
    "4A": "MEX",
    "4B": "MEX",
    "4C": "MEX",
    "4D": "PHL",
    "4E": "PHL",
    "4F": "PHL",
    "4G": "PHL",
    "4H": "PHL",
    "4I": "PHL",
    "4J": "AZE",
    "4K": "AZE",
    "4L": "GEO",
    "4M": "VEN",
    "4O": "MNE",
    "4P": "LKA",
    "4Q": "LKA",
    "4R": "LKA",
    "4S": "LKA",
    "4T": "PER",
    "4U": "UNO",
    "4V": "HTI",
    "4W": "TLS",
    "4X": "ISR",
    "4Y": "ICA",
    "4Z": "ISR",
    "5A": "LBY",
    "5B": "CYP",
    "5C": "MAR",
    "5D": "MAR",
    "5E": "MAR",
    "5F": "MAR",
    "5G": "MAR",
    "5H": "TZA",
    "5I": "TZA",
    "5J": "COL",
    "5K": "COL",
    "5L": "LBR",
    "5M": "LBR",
    "5N": "NGA",
    "5O": "NGA",
    "5P": "DNK",
    "5Q": "DNK",
    "5R": "MDG",
    "5S": "MDG",
    "5T": "MRT",
    "5U": "NER",
    "5V": "TGO",
    "5W": "WSM",
    "5X": "UGA",
    "5Y": "KEN",
    "5Z": "KEN",
    "6A": "EGY",
    "6B": "EGY",
    "6C": "SYR",
    "6D": "MEX",
    "6E": "MEX",
    "6F": "MEX",
    "6G": "MEX",
    "6H": "MEX",
    "6I": "MEX",
    "6J": "MEX",
    "6K": "KOR",
    "6L": "KOR",
    "6M": "KOR",
    "6N": "KOR",
    "6O": "SOM",
    "6P": "PAK",
    "6Q": "PAK",
    "6R": "PAK",
    "6S": "PAK",
    "6T": "SDN",
    "6U": "SDN",
    "6V": "SEN",
    "6W": "SEN",
    "6X": "MDG",
    "6Y": "JAM",
    "6Z": "LBR",
    "7A": "IDN",
    "7B": "IDN",
    "7C": "IDN",
    "7D": "IDN",
    "7E": "IDN",
    "7F": "IDN",
    "7G": "IDN",
    "7H": "IDN",
    "7I": "IDN",
    "7J": "JPN",
    "7K": "JPN",
    "7L": "JPN",
    "7M": "JPN",
    "7N": "JPN",
    "7O": "YEM",
    "7P": "LSO",
    "7Q": "MWI",
    "7R": "DZA",
    "7S": "SWE",
    "7T": "DZA",
    "7U": "DZA",
    "7V": "DZA",
    "7W": "DZA",
    "7X": "DZA",
    "7Y": "DZA",
    "7Z": "SAU",
    "8A": "IDN",
    "8B": "IDN",
    "8C": "IDN",
    "8D": "IDN",
    "8E": "IDN",
    "8F": "IDN",
    "8G": "IDN",
    "8H": "IDN",
    "8I": "IDN",
    "8J": "JPN",
    "8K": "JPN",
    "8L": "JPN",
    "8M": "JPN",
    "8N": "JPN",
    "8O": "BWA",
    "8P": "BRB",
    "8Q": "MDV",
    "8R": "GUY",
    "8S": "SWE",
    "8T": "IND",
    "8U": "IND",
    "8V": "IND",
    "8W": "IND",
    "8X": "IND",
    "8Y": "IND",
    "8Z": "SAU",
    "9A": "HRV",
    "9B": "IRN",
    "9C": "IRN",
    "9D": "IRN",
    "9E": "ETH",
    "9F": "ETH",
    "9G": "GHA",
    "9H": "MLT",
    "9I": "ZMB",
    "9J": "ZMB",
    "9K": "KWT",
    "9L": "SLE",
    "9M": "MYS",
    "9N": "NPL",
    "9O": "COD",
    "9P": "COD",
    "9Q": "COD",
    "9R": "COD",
    "9S": "COD",
    "9T": "COD",
    "9U": "BDI",
    "9V": "SGP",
    "9W": "MYS",
    "9X": "RWA",
    "9Y": "TTO",
    "9Z": "TTO",
}


ITU_COUNTRY_NAMES = {
    # Código ITU: { 'es': 'Nombre en español', 'en': 'Country name in English' }
    "USA": {"es": "Estados Unidos", "en": "United States"},
    "ESP": {"es": "España", "en": "Spain"},
    "PAK": {"es": "Pakistán", "en": "Pakistan"},
    "IND": {"es": "India", "en": "India"},
    "AUS": {"es": "Australia", "en": "Australia"},
    "ARG": {"es": "Argentina", "en": "Argentina"},
    "BWA": {"es": "Botsuana", "en": "Botswana"},
    "TON": {"es": "Tonga", "en": "Tonga"},
    "OMN": {"es": "Omán", "en": "Oman"},
    "BTN": {"es": "Bután", "en": "Bhutan"},
    "ARE": {"es": "Emiratos Árabes Unidos", "en": "United Arab Emirates"},
    "QAT": {"es": "Catar", "en": "Qatar"},
    "LBR": {"es": "Liberia", "en": "Liberia"},
    "BHR": {"es": "Baréin", "en": "Bahrain"},
    "CHN": {"es": "China", "en": "China"},
    "TWN": {"es": "Taiwán", "en": "Taiwan"},
    "CHL": {"es": "Chile", "en": "Chile"},
    "CAN": {"es": "Canadá", "en": "Canada"},
    "CUB": {"es": "Cuba", "en": "Cuba"},
    "MAR": {"es": "Marruecos", "en": "Morocco"},
    "BOL": {"es": "Bolivia", "en": "Bolivia"},
    "PRT": {"es": "Portugal", "en": "Portugal"},
    "URY": {"es": "Uruguay", "en": "Uruguay"},
    "NRU": {"es": "Nauru", "en": "Nauru"},
    "AND": {"es": "Andorra", "en": "Andorra"},
    "CYP": {"es": "Chipre", "en": "Cyprus"},
    "GMB": {"es": "Gambia", "en": "Gambia"},
    "BHS": {"es": "Bahamas", "en": "Bahamas"},
    "WMO": {
        "es": "Organización Meteorológica Mundial",
        "en": "World Meteorological Organization",
    },
    "MOZ": {"es": "Mozambique", "en": "Mozambique"},
    "DEU": {"es": "Alemania", "en": "Germany"},
    "KOR": {"es": "Corea del Sur", "en": "South Korea"},
    "PHL": {"es": "Filipinas", "en": "Philippines"},
    "AGO": {"es": "Angola", "en": "Angola"},
    "CPV": {"es": "Cabo Verde", "en": "Cape Verde"},
    "COM": {"es": "Comoras", "en": "Comoros"},
    "UKR": {"es": "Ucrania", "en": "Ukraine"},
    "IRL": {"es": "Irlanda", "en": "Ireland"},
    "ARM": {"es": "Armenia", "en": "Armenia"},
    "IRN": {"es": "Irán", "en": "Iran"},
    "MDA": {"es": "Moldavia", "en": "Moldova"},
    "EST": {"es": "Estonia", "en": "Estonia"},
    "ETH": {"es": "Etiopía", "en": "Ethiopia"},
    "BLR": {"es": "Bielorrusia", "en": "Belarus"},
    "KGZ": {"es": "Kirguistán", "en": "Kyrgyzstan"},
    "TJK": {"es": "Tayikistán", "en": "Tajikistan"},
    "TKM": {"es": "Turkmenistán", "en": "Turkmenistan"},
    "THA": {"es": "Tailandia", "en": "Thailand"},
    "ERI": {"es": "Eritrea", "en": "Eritrea"},
    "PSE": {"es": "Palestina", "en": "Palestine"},
    "COK": {"es": "Islas Cook", "en": "Cook Islands"},
    "NIU": {"es": "Niue", "en": "Niue"},
    "BIH": {"es": "Bosnia y Herzegovina", "en": "Bosnia and Herzegovina"},
    "FRA": {"es": "Francia", "en": "France"},
    "GBR": {"es": "Reino Unido", "en": "United Kingdom"},
    "HUN": {"es": "Hungría", "en": "Hungary"},
    "CHE": {"es": "Suiza", "en": "Switzerland"},
    "LIE": {"es": "Liechtenstein", "en": "Liechtenstein"},
    "ECU": {"es": "Ecuador", "en": "Ecuador"},
    "POL": {"es": "Polonia", "en": "Poland"},
    "HTI": {"es": "Haití", "en": "Haiti"},
    "DOM": {"es": "República Dominicana", "en": "Dominican Republic"},
    "COL": {"es": "Colombia", "en": "Colombia"},
    "PRK": {"es": "Corea del Norte", "en": "North Korea"},
    "IRQ": {"es": "Irak", "en": "Iraq"},
    "PAN": {"es": "Panamá", "en": "Panama"},
    "HND": {"es": "Honduras", "en": "Honduras"},
    "NIC": {"es": "Nicaragua", "en": "Nicaragua"},
    "SLV": {"es": "El Salvador", "en": "El Salvador"},
    "VAT": {"es": "Ciudad del Vaticano", "en": "Vatican City"},
    "SAU": {"es": "Arabia Saudita", "en": "Saudi Arabia"},
    "CYP": {"es": "Chipre", "en": "Cyprus"},
    "SLB": {"es": "Islas Salomón", "en": "Solomon Islands"},
    "AUT": {"es": "Austria", "en": "Austria"},
    "FIN": {"es": "Finlandia", "en": "Finland"},
    "CZE": {"es": "Chequia", "en": "Czech Republic"},
    "SVK": {"es": "Eslovaquia", "en": "Slovakia"},
    "BEL": {"es": "Bélgica", "en": "Belgium"},
    "DNK": {"es": "Dinamarca", "en": "Denmark"},
    "NLD": {"es": "Países Bajos", "en": "Netherlands"},
    "ANT": {"es": "Antillas Neerlandesas", "en": "Netherlands Antilles"},
    "IDN": {"es": "Indonesia", "en": "Indonesia"},
    "BRA": {"es": "Brasil", "en": "Brazil"},
    "SUR": {"es": "Surinam", "en": "Suriname"},
    "PNG": {"es": "Papúa Nueva Guinea", "en": "Papua New Guinea"},
    "ABW": {"es": "Aruba", "en": "Aruba"},
    "RUS": {"es": "Rusia", "en": "Russia"},
    "SWE": {"es": "Suecia", "en": "Sweden"},
    "EGY": {"es": "Egipto", "en": "Egypt"},
    "SDN": {"es": "Sudán", "en": "Sudan"},
    "GRC": {"es": "Grecia", "en": "Greece"},
    "BGD": {"es": "Bangladés", "en": "Bangladesh"},
    "SVN": {"es": "Eslovenia", "en": "Slovenia"},
    "SGP": {"es": "Singapur", "en": "Singapore"},
    "SYC": {"es": "Seychelles", "en": "Seychelles"},
    "ZAF": {"es": "Sudáfrica", "en": "South Africa"},
    "STP": {"es": "Santo Tomé y Príncipe", "en": "São Tomé and Príncipe"},
    "TUR": {"es": "Turquía", "en": "Turkey"},
    "GTM": {"es": "Guatemala", "en": "Guatemala"},
    "CRI": {"es": "Costa Rica", "en": "Costa Rica"},
    "ISL": {"es": "Islandia", "en": "Iceland"},
    "CMR": {"es": "Camerún", "en": "Cameroon"},
    "CAF": {"es": "República Centroafricana", "en": "Central African Republic"},
    "COG": {"es": "República del Congo", "en": "Republic of the Congo"},
    "GAB": {"es": "Gabón", "en": "Gabon"},
    "TUN": {"es": "Túnez", "en": "Tunisia"},
    "TCD": {"es": "Chad", "en": "Chad"},
    "CIV": {"es": "Costa de Marfil", "en": "Ivory Coast"},
    "BEN": {"es": "Benín", "en": "Benin"},
    "MLI": {"es": "Malí", "en": "Mali"},
    "TUV": {"es": "Tuvalu", "en": "Tuvalu"},
    "KIR": {"es": "Kiribati", "en": "Kiribati"},
    "SOM": {"es": "Somalia", "en": "Somalia"},
    "AFG": {"es": "Afganistán", "en": "Afghanistan"},
    "SMR": {"es": "San Marino", "en": "San Marino"},
    "PLW": {"es": "Palaos", "en": "Palau"},
    "UZB": {"es": "Uzbekistán", "en": "Uzbekistan"},
    "KAZ": {"es": "Kazajistán", "en": "Kazakhstan"},
    "AUS": {"es": "Australia", "en": "Australia"},
    "ATG": {"es": "Antigua y Barbuda", "en": "Antigua and Barbuda"},
    "BLZ": {"es": "Belice", "en": "Belize"},
    "KNA": {"es": "San Cristóbal y Nieves", "en": "Saint Kitts and Nevis"},
    "NAM": {"es": "Namibia", "en": "Namibia"},
    "FSM": {"es": "Micronesia", "en": "Micronesia"},
    "MHL": {"es": "Islas Marshall", "en": "Marshall Islands"},
    "BRN": {"es": "Brunéi", "en": "Brunei"},
    "MEX": {"es": "México", "en": "Mexico"},
    "HKG": {"es": "Hong Kong", "en": "Hong Kong"},
    "LAO": {"es": "Laos", "en": "Laos"},
    "MAC": {"es": "Macao", "en": "Macau"},
    "MMR": {"es": "Birmania", "en": "Myanmar"},
    "VNM": {"es": "Vietnam", "en": "Vietnam"},
    "GIN": {"es": "Guinea", "en": "Guinea"},
    "MCO": {"es": "Mónaco", "en": "Monaco"},
    "MUS": {"es": "Mauricio", "en": "Mauritius"},
    "GNQ": {"es": "Guinea Ecuatorial", "en": "Equatorial Guinea"},
    "SWZ": {"es": "Suazilandia", "en": "Eswatini"},
    "FJI": {"es": "Fiyi", "en": "Fiji"},
    "AZE": {"es": "Azerbaiyán", "en": "Azerbaijan"},
    "GEO": {"es": "Georgia", "en": "Georgia"},
    "VEN": {"es": "Venezuela", "en": "Venezuela"},
    "MNE": {"es": "Montenegro", "en": "Montenegro"},
    "LKA": {"es": "Sri Lanka", "en": "Sri Lanka"},
    "UNO": {"es": "Naciones Unidas", "en": "United Nations"},
    "TLS": {"es": "Timor Oriental", "en": "Timor-Leste"},
    "ISR": {"es": "Israel", "en": "Israel"},
    "ICA": {
        "es": "Organización de Aviación Civil Internacional",
        "en": "International Civil Aviation Organization",
    },
    "LBY": {"es": "Libia", "en": "Libya"},
    "NGA": {"es": "Nigeria", "en": "Nigeria"},
    "MDG": {"es": "Madagascar", "en": "Madagascar"},
    "MRT": {"es": "Mauritania", "en": "Mauritania"},
    "NER": {"es": "Níger", "en": "Niger"},
    "TGO": {"es": "Togo", "en": "Togo"},
    "WSM": {"es": "Samoa", "en": "Samoa"},
    "UGA": {"es": "Uganda", "en": "Uganda"},
    "KEN": {"es": "Kenia", "en": "Kenya"},
    "JAM": {"es": "Jamaica", "en": "Jamaica"},
    "HRV": {"es": "Croacia", "en": "Croatia"},
    "MLT": {"es": "Malta", "en": "Malta"},
    "ZMB": {"es": "Zambia", "en": "Zambia"},
    "KWT": {"es": "Kuwait", "en": "Kuwait"},
    "SLE": {"es": "Sierra Leona", "en": "Sierra Leone"},
    "MYS": {"es": "Malasia", "en": "Malaysia"},
    "NPL": {"es": "Nepal", "en": "Nepal"},
    "COD": {
        "es": "República Democrática del Congo",
        "en": "Democratic Republic of the Congo",
    },
    "BDI": {"es": "Burundi", "en": "Burundi"},
    "RWA": {"es": "Ruanda", "en": "Rwanda"},
    "TTO": {"es": "Trinidad y Tobago", "en": "Trinidad and Tobago"},
    "ZWE": {"es": "Zimbabue", "en": "Zimbabwe"},
    "MKD": {"es": "Macedonia del Norte", "en": "North Macedonia"},
    "SSD": {"es": "Sudán del Sur", "en": "South Sudan"},
    "ALB": {"es": "Albania", "en": "Albania"},
    "NZL": {"es": "Nueva Zelanda", "en": "New Zealand"},
}


def callsign_to_country(callsign: str) -> str | None:
    """
    Devuelve el país ITU para un indicativo dado.
    Args:
        callsign (str): Indicativo completo (puede incluir /).
    Returns:
        str | None: Código de país ITU o None si no se encuentra.
    """
    parts = callsign.split("/")
    sorted_parts = sorted(parts, key=len)
    for part in sorted_parts:
        upper_part = part.upper()
        if upper_part in ITU_PREFIXES:
            return ITU_PREFIXES[upper_part]
    for part in sorted_parts:
        for length in range(1, len(part) + 1):
            prefix = part[:length].upper()
            if prefix in ITU_PREFIXES:
                return ITU_PREFIXES[prefix]
    return None
