ITU_COUNTRY_NAMES = {
    # Código ITU: { 'es': 'Nombre en español', 'en': 'Country name in English' }
    "USA": {"es": "Estados Unidos", "en": "United States"},
    "ESP": {"es": "España", "en": "Spain"},
    "PAK": {"es": "Pakistán", "en": "Pakistan"},
    "IND": {"es": "India", "en": "India"},
    "AUS": {"es": "Australia", "en": "Australia"},
    "ARG": {"es": "Argentina", "en": "Argentina"},
    "BWA": {"es": "Botsuana", "en": "Botswana"},
    "TON": {"es": "Tonga", "en": "Tonga"},
    "OMN": {"es": "Omán", "en": "Oman"},
    "BTN": {"es": "Bután", "en": "Bhutan"},
    "ARE": {"es": "Emiratos Árabes Unidos", "en": "United Arab Emirates"},
    "QAT": {"es": "Catar", "en": "Qatar"},
    "LBR": {"es": "Liberia", "en": "Liberia"},
    "BHR": {"es": "Baréin", "en": "Bahrain"},
    "CHN": {"es": "China", "en": "China"},
    "TWN": {"es": "Taiwán", "en": "Taiwan"},
    "CHL": {"es": "Chile", "en": "Chile"},
    "CAN": {"es": "Canadá", "en": "Canada"},
    "CUB": {"es": "Cuba", "en": "Cuba"},
    "MAR": {"es": "Marruecos", "en": "Morocco"},
    "BOL": {"es": "Bolivia", "en": "Bolivia"},
    "PRT": {"es": "Portugal", "en": "Portugal"},
    "URY": {"es": "Uruguay", "en": "Uruguay"},
    "NRU": {"es": "Nauru", "en": "Nauru"},
    "AND": {"es": "Andorra", "en": "Andorra"},
    "CYP": {"es": "Chipre", "en": "Cyprus"},
    "GMB": {"es": "Gambia", "en": "Gambia"},
    "BHS": {"es": "Bahamas", "en": "Bahamas"},
    "WMO": {
        "es": "Organización Meteorológica Mundial",
        "en": "World Meteorological Organization",
    },
    "MOZ": {"es": "Mozambique", "en": "Mozambique"},
    "DEU": {"es": "Alemania", "en": "Germany"},
    "KOR": {"es": "Corea del Sur", "en": "South Korea"},
    "PHL": {"es": "Filipinas", "en": "Philippines"},
    "AGO": {"es": "Angola", "en": "Angola"},
    "CPV": {"es": "Cabo Verde", "en": "Cape Verde"},
    "COM": {"es": "Comoras", "en": "Comoros"},
    "UKR": {"es": "Ucrania", "en": "Ukraine"},
    "IRL": {"es": "Irlanda", "en": "Ireland"},
    "ARM": {"es": "Armenia", "en": "Armenia"},
    "IRN": {"es": "Irán", "en": "Iran"},
    "MDA": {"es": "Moldavia", "en": "Moldova"},
    "EST": {"es": "Estonia", "en": "Estonia"},
    "ETH": {"es": "Etiopía", "en": "Ethiopia"},
    "BLR": {"es": "Bielorrusia", "en": "Belarus"},
    "KGZ": {"es": "Kirguistán", "en": "Kyrgyzstan"},
    "TJK": {"es": "Tayikistán", "en": "Tajikistan"},
    "TKM": {"es": "Turkmenistán", "en": "Turkmenistan"},
    "THA": {"es": "Tailandia", "en": "Thailand"},
    "ERI": {"es": "Eritrea", "en": "Eritrea"},
    "PSE": {"es": "Palestina", "en": "Palestine"},
    "COK": {"es": "Islas Cook", "en": "Cook Islands"},
    "NIU": {"es": "Niue", "en": "Niue"},
    "BIH": {"es": "Bosnia y Herzegovina", "en": "Bosnia and Herzegovina"},
    "FRA": {"es": "Francia", "en": "France"},
    "GBR": {"es": "Reino Unido", "en": "United Kingdom"},
    "HUN": {"es": "Hungría", "en": "Hungary"},
    "CHE": {"es": "Suiza", "en": "Switzerland"},
    "LIE": {"es": "Liechtenstein", "en": "Liechtenstein"},
    "ECU": {"es": "Ecuador", "en": "Ecuador"},
    "POL": {"es": "Polonia", "en": "Poland"},
    "HTI": {"es": "Haití", "en": "Haiti"},
    "DOM": {"es": "República Dominicana", "en": "Dominican Republic"},
    "COL": {"es": "Colombia", "en": "Colombia"},
    "PRK": {"es": "Corea del Norte", "en": "North Korea"},
    "IRQ": {"es": "Irak", "en": "Iraq"},
    "PAN": {"es": "Panamá", "en": "Panama"},
    "HND": {"es": "Honduras", "en": "Honduras"},
    "NIC": {"es": "Nicaragua", "en": "Nicaragua"},
    "SLV": {"es": "El Salvador", "en": "El Salvador"},
    "VAT": {"es": "Ciudad del Vaticano", "en": "Vatican City"},
    "SAU": {"es": "Arabia Saudita", "en": "Saudi Arabia"},
    "CYP": {"es": "Chipre", "en": "Cyprus"},
    "SLB": {"es": "Islas Salomón", "en": "Solomon Islands"},
    "AUT": {"es": "Austria", "en": "Austria"},
    "FIN": {"es": "Finlandia", "en": "Finland"},
    "CZE": {"es": "Chequia", "en": "Czech Republic"},
    "SVK": {"es": "Eslovaquia", "en": "Slovakia"},
    "BEL": {"es": "Bélgica", "en": "Belgium"},
    "DNK": {"es": "Dinamarca", "en": "Denmark"},
    "NLD": {"es": "Países Bajos", "en": "Netherlands"},
    "ANT": {"es": "Antillas Neerlandesas", "en": "Netherlands Antilles"},
    "IDN": {"es": "Indonesia", "en": "Indonesia"},
    "BRA": {"es": "Brasil", "en": "Brazil"},
    "SUR": {"es": "Surinam", "en": "Suriname"},
    "PNG": {"es": "Papúa Nueva Guinea", "en": "Papua New Guinea"},
    "ABW": {"es": "Aruba", "en": "Aruba"},
    "RUS": {"es": "Rusia", "en": "Russia"},
    "SWE": {"es": "Suecia", "en": "Sweden"},
    "EGY": {"es": "Egipto", "en": "Egypt"},
    "SDN": {"es": "Sudán", "en": "Sudan"},
    "GRC": {"es": "Grecia", "en": "Greece"},
    "BGD": {"es": "Bangladés", "en": "Bangladesh"},
    "SVN": {"es": "Eslovenia", "en": "Slovenia"},
    "SGP": {"es": "Singapur", "en": "Singapore"},
    "SYC": {"es": "Seychelles", "en": "Seychelles"},
    "ZAF": {"es": "Sudáfrica", "en": "South Africa"},
    "STP": {"es": "Santo Tomé y Príncipe", "en": "São Tomé and Príncipe"},
    "TUR": {"es": "Turquía", "en": "Turkey"},
    "GTM": {"es": "Guatemala", "en": "Guatemala"},
    "CRI": {"es": "Costa Rica", "en": "Costa Rica"},
    "ISL": {"es": "Islandia", "en": "Iceland"},
    "CMR": {"es": "Camerún", "en": "Cameroon"},
    "CAF": {"es": "República Centroafricana", "en": "Central African Republic"},
    "ABW": {"es": "Aruba", "en": "Aruba"},
    "AFG": {"es": "Afganistán", "en": "Afghanistan"},
    "ALB": {"es": "Albania", "en": "Albania"},
    "AGO": {"es": "Angola", "en": "Angola"},
    "AND": {"es": "Andorra", "en": "Andorra"},
    "ANT": {"es": "Antillas Neerlandesas", "en": "Netherlands Antilles"},
    "ATG": {"es": "Antigua y Barbuda", "en": "Antigua and Barbuda"},
    "AUT": {"es": "Austria", "en": "Austria"},
    "AZE": {"es": "Azerbaiyán", "en": "Azerbaijan"},
    "BDI": {"es": "Burundi", "en": "Burundi"},
    "BEL": {"es": "Bélgica", "en": "Belgium"},
    "BEN": {"es": "Benín", "en": "Benin"},
    "BFA": {"es": "Burkina Faso", "en": "Burkina Faso"},
    "BGR": {"es": "Bulgaria", "en": "Bulgaria"},
    "BGD": {"es": "Bangladés", "en": "Bangladesh"},
    "BHR": {"es": "Baréin", "en": "Bahrain"},
    "BHS": {"es": "Bahamas", "en": "Bahamas"},
    "BIH": {"es": "Bosnia y Herzegovina", "en": "Bosnia and Herzegovina"},
    "BLR": {"es": "Bielorrusia", "en": "Belarus"},
    "BLZ": {"es": "Belice", "en": "Belize"},
    "BOL": {"es": "Bolivia", "en": "Bolivia"},
    "BRA": {"es": "Brasil", "en": "Brazil"},
    "BRB": {"es": "Barbados", "en": "Barbados"},
    "BRN": {"es": "Brunéi", "en": "Brunei"},
    "BWA": {"es": "Botsuana", "en": "Botswana"},
    "CHN": {"es": "China", "en": "China"},
    "CIV": {"es": "Costa de Marfil", "en": "Ivory Coast"},
    "CMR": {"es": "Camerún", "en": "Cameroon"},
    "COD": {
        "es": "República Democrática del Congo",
        "en": "Democratic Republic of the Congo",
    },
    "COG": {"es": "República del Congo", "en": "Republic of the Congo"},
    "COL": {"es": "Colombia", "en": "Colombia"},
    "COM": {"es": "Comoras", "en": "Comoros"},
    "CPV": {"es": "Cabo Verde", "en": "Cape Verde"},
    "CRI": {"es": "Costa Rica", "en": "Costa Rica"},
    "CUB": {"es": "Cuba", "en": "Cuba"},
    "CYP": {"es": "Chipre", "en": "Cyprus"},
    "CZE": {"es": "Chequia", "en": "Czech Republic"},
    "DEU": {"es": "Alemania", "en": "Germany"},
    "DJI": {"es": "Yibuti", "en": "Djibouti"},
    "DMA": {"es": "Dominica", "en": "Dominica"},
    "DNK": {"es": "Dinamarca", "en": "Denmark"},
    "DOM": {"es": "República Dominicana", "en": "Dominican Republic"},
    "DZA": {"es": "Argelia", "en": "Algeria"},
    "ECU": {"es": "Ecuador", "en": "Ecuador"},
    "EGY": {"es": "Egipto", "en": "Egypt"},
    "ERI": {"es": "Eritrea", "en": "Eritrea"},
    "EST": {"es": "Estonia", "en": "Estonia"},
    "ETH": {"es": "Etiopía", "en": "Ethiopia"},
    "FIN": {"es": "Finlandia", "en": "Finland"},
    "FJI": {"es": "Fiyi", "en": "Fiji"},
    "FSM": {"es": "Micronesia", "en": "Micronesia"},
    "GAB": {"es": "Gabón", "en": "Gabon"},
    "GEO": {"es": "Georgia", "en": "Georgia"},
    "GHA": {"es": "Ghana", "en": "Ghana"},
    "GIN": {"es": "Guinea", "en": "Guinea"},
    "GMB": {"es": "Gambia", "en": "Gambia"},
    "GNB": {"es": "Guinea-Bisáu", "en": "Guinea-Bissau"},
    "GNQ": {"es": "Guinea Ecuatorial", "en": "Equatorial Guinea"},
    "GRC": {"es": "Grecia", "en": "Greece"},
    "GRD": {"es": "Granada", "en": "Grenada"},
    "GTM": {"es": "Guatemala", "en": "Guatemala"},
    "GUY": {"es": "Guyana", "en": "Guyana"},
    "HKG": {"es": "Hong Kong", "en": "Hong Kong"},
    "HND": {"es": "Honduras", "en": "Honduras"},
    "HRV": {"es": "Croacia", "en": "Croatia"},
    "HTI": {"es": "Haití", "en": "Haiti"},
    "HUN": {"es": "Hungría", "en": "Hungary"},
    "ICA": {
        "es": "Organización de Aviación Civil Internacional",
        "en": "International Civil Aviation Organization",
    },
    "IDN": {"es": "Indonesia", "en": "Indonesia"},
    "IND": {"es": "India", "en": "India"},
    "IRL": {"es": "Irlanda", "en": "Ireland"},
    "IRN": {"es": "Irán", "en": "Iran"},
    "IRQ": {"es": "Irak", "en": "Iraq"},
    "ISL": {"es": "Islandia", "en": "Iceland"},
    "ISR": {"es": "Israel", "en": "Israel"},
    "ITA": {"es": "Italia", "en": "Italy"},
    "JAM": {"es": "Jamaica", "en": "Jamaica"},
    "JOR": {"es": "Jordania", "en": "Jordan"},
    "JPN": {"es": "Japón", "en": "Japan"},
    "KAZ": {"es": "Kazajistán", "en": "Kazakhstan"},
    "KEN": {"es": "Kenia", "en": "Kenya"},
    "KGZ": {"es": "Kirguistán", "en": "Kyrgyzstan"},
    "KHM": {"es": "Camboya", "en": "Cambodia"},
    "KIR": {"es": "Kiribati", "en": "Kiribati"},
    "KNA": {"es": "San Cristóbal y Nieves", "en": "Saint Kitts and Nevis"},
    "KOR": {"es": "Corea del Sur", "en": "South Korea"},
    "KWT": {"es": "Kuwait", "en": "Kuwait"},
    "LAO": {"es": "Laos", "en": "Laos"},
    "LBN": {"es": "Líbano", "en": "Lebanon"},
    "LBR": {"es": "Liberia", "en": "Liberia"},
    "LBY": {"es": "Libia", "en": "Libya"},
    "LCA": {"es": "Santa Lucía", "en": "Saint Lucia"},
    "LIE": {"es": "Liechtenstein", "en": "Liechtenstein"},
    "LKA": {"es": "Sri Lanka", "en": "Sri Lanka"},
    "LSO": {"es": "Lesoto", "en": "Lesotho"},
    "LTU": {"es": "Lituania", "en": "Lithuania"},
    "LUX": {"es": "Luxemburgo", "en": "Luxembourg"},
    "LVA": {"es": "Letonia", "en": "Latvia"},
    "MAC": {"es": "Macao", "en": "Macau"},
    "MAR": {"es": "Marruecos", "en": "Morocco"},
    "MCO": {"es": "Mónaco", "en": "Monaco"},
    "MDA": {"es": "Moldavia", "en": "Moldova"},
    "MDG": {"es": "Madagascar", "en": "Madagascar"},
    "MDV": {"es": "Maldivas", "en": "Maldives"},
    "MEX": {"es": "México", "en": "Mexico"},
    "MHL": {"es": "Islas Marshall", "en": "Marshall Islands"},
    "MKD": {"es": "Macedonia del Norte", "en": "North Macedonia"},
    "MLI": {"es": "Malí", "en": "Mali"},
    "MLT": {"es": "Malta", "en": "Malta"},
    "MMR": {"es": "Birmania", "en": "Myanmar"},
    "MNE": {"es": "Montenegro", "en": "Montenegro"},
    "MNG": {"es": "Mongolia", "en": "Mongolia"},
    "MOZ": {"es": "Mozambique", "en": "Mozambique"},
    "MRT": {"es": "Mauritania", "en": "Mauritania"},
    "MUS": {"es": "Mauricio", "en": "Mauritius"},
    "MWI": {"es": "Malaui", "en": "Malawi"},
    "MYS": {"es": "Malasia", "en": "Malaysia"},
    "NAM": {"es": "Namibia", "en": "Namibia"},
    "NER": {"es": "Níger", "en": "Niger"},
    "NGA": {"es": "Nigeria", "en": "Nigeria"},
    "NIC": {"es": "Nicaragua", "en": "Nicaragua"},
    "NIU": {"es": "Niue", "en": "Niue"},
    "NLD": {"es": "Países Bajos", "en": "Netherlands"},
    "NOR": {"es": "Noruega", "en": "Norway"},
    "NPL": {"es": "Nepal", "en": "Nepal"},
    "NRU": {"es": "Nauru", "en": "Nauru"},
    "NZL": {"es": "Nueva Zelanda", "en": "New Zealand"},
    "OMN": {"es": "Omán", "en": "Oman"},
    "PAK": {"es": "Pakistán", "en": "Pakistan"},
    "PAN": {"es": "Panamá", "en": "Panama"},
    "PER": {"es": "Perú", "en": "Peru"},
    "PHL": {"es": "Filipinas", "en": "Philippines"},
    "PLW": {"es": "Palaos", "en": "Palau"},
    "PNG": {"es": "Papúa Nueva Guinea", "en": "Papua New Guinea"},
    "POL": {"es": "Polonia", "en": "Poland"},
    "PRK": {"es": "Corea del Norte", "en": "North Korea"},
    "PRT": {"es": "Portugal", "en": "Portugal"},
    "PRY": {"es": "Paraguay", "en": "Paraguay"},
    "PSE": {"es": "Palestina", "en": "Palestine"},
    "QAT": {"es": "Catar", "en": "Qatar"},
    "ROU": {"es": "Rumanía", "en": "Romania"},
    "RUS": {"es": "Rusia", "en": "Russia"},
    "RWA": {"es": "Ruanda", "en": "Rwanda"},
    "SAU": {"es": "Arabia Saudita", "en": "Saudi Arabia"},
    "SDN": {"es": "Sudán", "en": "Sudan"},
    "SEN": {"es": "Senegal", "en": "Senegal"},
    "SGP": {"es": "Singapur", "en": "Singapore"},
    "SLB": {"es": "Islas Salomón", "en": "Solomon Islands"},
    "SLE": {"es": "Sierra Leona", "en": "Sierra Leone"},
    "SLV": {"es": "El Salvador", "en": "El Salvador"},
    "SMR": {"es": "San Marino", "en": "San Marino"},
    "SOM": {"es": "Somalia", "en": "Somalia"},
    "SRB": {"es": "Serbia", "en": "Serbia"},
    "SSD": {"es": "Sudán del Sur", "en": "South Sudan"},
    "STP": {"es": "Santo Tomé y Príncipe", "en": "São Tomé and Príncipe"},
    "SUR": {"es": "Surinam", "en": "Suriname"},
    "SVK": {"es": "Eslovaquia", "en": "Slovakia"},
    "SVN": {"es": "Eslovenia", "en": "Slovenia"},
    "SWE": {"es": "Suecia", "en": "Sweden"},
    "SWZ": {"es": "Suazilandia", "en": "Eswatini"},
    "SYC": {"es": "Seychelles", "en": "Seychelles"},
    "SYR": {"es": "Siria", "en": "Syria"},
    "TCD": {"es": "Chad", "en": "Chad"},
    "TGO": {"es": "Togo", "en": "Togo"},
    "THA": {"es": "Tailandia", "en": "Thailand"},
    "TJK": {"es": "Tayikistán", "en": "Tajikistan"},
    "TKM": {"es": "Turkmenistán", "en": "Turkmenistan"},
    "TLS": {"es": "Timor Oriental", "en": "Timor-Leste"},
    "TON": {"es": "Tonga", "en": "Tonga"},
    "TTO": {"es": "Trinidad y Tobago", "en": "Trinidad and Tobago"},
    "TUN": {"es": "Túnez", "en": "Tunisia"},
    "TUR": {"es": "Turquía", "en": "Turkey"},
    "TUV": {"es": "Tuvalu", "en": "Tuvalu"},
    "TWN": {"es": "Taiwán", "en": "Taiwan"},
    "TZA": {"es": "Tanzania", "en": "Tanzania"},
    "UGA": {"es": "Uganda", "en": "Uganda"},
    "UKR": {"es": "Ucrania", "en": "Ukraine"},
    "UNO": {"es": "Naciones Unidas", "en": "United Nations"},
    "URY": {"es": "Uruguay", "en": "Uruguay"},
    "USA": {"es": "Estados Unidos", "en": "United States"},
    "UZB": {"es": "Uzbekistán", "en": "Uzbekistan"},
    "VAT": {"es": "Ciudad del Vaticano", "en": "Vatican City"},
    "VCT": {
        "es": "San Vicente y las Granadinas",
        "en": "Saint Vincent and the Grenadines",
    },
    "VEN": {"es": "Venezuela", "en": "Venezuela"},
    "VNM": {"es": "Vietnam", "en": "Vietnam"},
    "VUT": {"es": "Vanuatu", "en": "Vanuatu"},
    "WMO": {
        "es": "Organización Meteorológica Mundial",
        "en": "World Meteorological Organization",
    },
    "WSM": {"es": "Samoa", "en": "Samoa"},
    "YEM": {"es": "Yemen", "en": "Yemen"},
    "ZAF": {"es": "Sudáfrica", "en": "South Africa"},
    "ZMB": {"es": "Zambia", "en": "Zambia"},
    "ZWE": {"es": "Zimbabue", "en": "Zimbabwe"},
    "COG": {"es": "República del Congo", "en": "Republic of the Congo"},
    "GAB": {"es": "Gabón", "en": "Gabon"},
    "TUN": {"es": "Túnez", "en": "Tunisia"},
    "TCD": {"es": "Chad", "en": "Chad"},
    "CIV": {"es": "Costa de Marfil", "en": "Ivory Coast"},
    "BEN": {"es": "Benín", "en": "Benin"},
    "MLI": {"es": "Malí", "en": "Mali"},
    "TUV": {"es": "Tuvalu", "en": "Tuvalu"},
    "KIR": {"es": "Kiribati", "en": "Kiribati"},
    "SOM": {"es": "Somalia", "en": "Somalia"},
    "AFG": {"es": "Afganistán", "en": "Afghanistan"},
    "SMR": {"es": "San Marino", "en": "San Marino"},
    "PLW": {"es": "Palaos", "en": "Palau"},
    "UZB": {"es": "Uzbekistán", "en": "Uzbekistan"},
    "KAZ": {"es": "Kazajistán", "en": "Kazakhstan"},
    "AUS": {"es": "Australia", "en": "Australia"},
    "ATG": {"es": "Antigua y Barbuda", "en": "Antigua and Barbuda"},
    "BLZ": {"es": "Belice", "en": "Belize"},
    "KNA": {"es": "San Cristóbal y Nieves", "en": "Saint Kitts and Nevis"},
    "NAM": {"es": "Namibia", "en": "Namibia"},
    "FSM": {"es": "Micronesia", "en": "Micronesia"},
    "MHL": {"es": "Islas Marshall", "en": "Marshall Islands"},
    "BRN": {"es": "Brunéi", "en": "Brunei"},
    "MEX": {"es": "México", "en": "Mexico"},
    "HKG": {"es": "Hong Kong", "en": "Hong Kong"},
    "LAO": {"es": "Laos", "en": "Laos"},
    "MAC": {"es": "Macao", "en": "Macau"},
    "MMR": {"es": "Birmania", "en": "Myanmar"},
    "VNM": {"es": "Vietnam", "en": "Vietnam"},
    "GIN": {"es": "Guinea", "en": "Guinea"},
    "MCO": {"es": "Mónaco", "en": "Monaco"},
    "MUS": {"es": "Mauricio", "en": "Mauritius"},
    "GNQ": {"es": "Guinea Ecuatorial", "en": "Equatorial Guinea"},
    "SWZ": {"es": "Suazilandia", "en": "Eswatini"},
    "FJI": {"es": "Fiyi", "en": "Fiji"},
    "AZE": {"es": "Azerbaiyán", "en": "Azerbaijan"},
    "GEO": {"es": "Georgia", "en": "Georgia"},
    "VEN": {"es": "Venezuela", "en": "Venezuela"},
    "MNE": {"es": "Montenegro", "en": "Montenegro"},
    "LKA": {"es": "Sri Lanka", "en": "Sri Lanka"},
    "UNO": {"es": "Naciones Unidas", "en": "United Nations"},
    "TLS": {"es": "Timor Oriental", "en": "Timor-Leste"},
    "ISR": {"es": "Israel", "en": "Israel"},
    "ICA": {
        "es": "Organización de Aviación Civil Internacional",
        "en": "International Civil Aviation Organization",
    },
    "LBY": {"es": "Libia", "en": "Libya"},
    "NGA": {"es": "Nigeria", "en": "Nigeria"},
    "MDG": {"es": "Madagascar", "en": "Madagascar"},
    "MRT": {"es": "Mauritania", "en": "Mauritania"},
    "NER": {"es": "Níger", "en": "Niger"},
    "TGO": {"es": "Togo", "en": "Togo"},
    "WSM": {"es": "Samoa", "en": "Samoa"},
    "UGA": {"es": "Uganda", "en": "Uganda"},
    "KEN": {"es": "Kenia", "en": "Kenya"},
    "JAM": {"es": "Jamaica", "en": "Jamaica"},
    "HRV": {"es": "Croacia", "en": "Croatia"},
    "MLT": {"es": "Malta", "en": "Malta"},
    "ZMB": {"es": "Zambia", "en": "Zambia"},
    "KWT": {"es": "Kuwait", "en": "Kuwait"},
    "SLE": {"es": "Sierra Leona", "en": "Sierra Leone"},
    "MYS": {"es": "Malasia", "en": "Malaysia"},
    "NPL": {"es": "Nepal", "en": "Nepal"},
    "COD": {
        "es": "República Democrática del Congo",
        "en": "Democratic Republic of the Congo",
    },
    "BDI": {"es": "Burundi", "en": "Burundi"},
    "RWA": {"es": "Ruanda", "en": "Rwanda"},
    "TTO": {"es": "Trinidad y Tobago", "en": "Trinidad and Tobago"},
    "ZWE": {"es": "Zimbabue", "en": "Zimbabwe"},
    "MKD": {"es": "Macedonia del Norte", "en": "North Macedonia"},
    "SSD": {"es": "Sudán del Sur", "en": "South Sudan"},
    "ALB": {"es": "Albania", "en": "Albania"},
    "NZL": {"es": "Nueva Zelanda", "en": "New Zealand"},
}
