from __future__ import annotations

from typing import Iterable, List, Optional, Protocol
from ...domain.models import RadioOperator


class IRadioOperatorsRepo(Protocol):
    def init_schema(self) -> None: ...

    def upsert_many(self, items: Iterable[RadioOperator]) -> None: ...

    def upsert_one(self, item: RadioOperator) -> None: ...

    def list_all(self) -> List[RadioOperator]: ...

    def delete_by_callsign(self, callsign: str) -> None: ...

    def disable_by_callsign(self, callsign: str) -> None: ...
